title: UniqueShip
description: A labeled maritime acoustic dataset coming soon.
url: "https://uniqueshipdata.org"
baseurl: ""

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - tailwind.config.js

defaults:
  - scope:
      path: ""
    values:
      layout: default
